Zomm 60: 기본 환경 구성
mmtechcommunity/zomm-fe pull request #1
Opened 2021-08-12 12:56 UTC by yourankim

2021-08-17 06:31 UTC, rostradamus approved these changes
👍

2021-08-17 07:42 UTC, rostradamus requested changes

2021-08-17 07:42 UTC, rostradamus commented on src/pages/sample.tsx
> +      {list.map((item: Data) => <li>{item.message}</li>)}
Array로 list 렌더링을 하기 때문에 key를 추가하면 error 메세지를 없앨수 있을것 같습니다!  https://ko.reactjs.org/docs/lists-and-keys.html
```
{list.map((item: Data) =><li key={item.id}>{item.id}: {item.message}</li>)}
```

2021-08-17 14:53 UTC, rostradamus commented
@PullStackCoder 님 질문 관련
1) id는 카카오계정id라면, uuid 같은 필드 필요 없을까요?
- 저희 서버쪽 유저 id는 users 테이블 안에 id입니다. OAuth 연동 대한 식별자는 oauth_links 테이블에 link_id(카카오 계정 id) + auth_type("KAKAO" or "APPLE" or etc) Composite key로 구성되어 있습니다. (참조: https://www.notion.so/zomm/e079c33c4af54933bd264d8e77da7fc1#0c080614edcf4e01bee0c1d41bc4d8e6)
2) 음mm에서 가져와야 할 필드 : 계정id, nickname, 자기소개/프사(BLOB), …
- 계정id = users table의 id column
- 닉네임은 users table에 name column과 동일하다고 생각하셔도 좋겠습니다.
- 이 부분들은 나중에 기능을 추가하면서 users table에 `ALTER TABLE users ADD COLUMN ...`  방식으로 넣어도 될것 같구요. 아니면 profile이라는 테이블을 따로 만들어서 users table에 join 하는 형식으로 가져가도 될것 같습니다.
3) last_login_time, device(iOS/Android)
- 이부분은 따로 ticket을 생성해서 기능 구현을 하면 좋겠네요.
4) last_login_ip (privacy 이슈가 있을 수도)
- 3)과 동일

2021-08-19 15:43 UTC, yourankim commented on src/pages/sample.tsx
> +      }catch(e) {
감사합니다!! prettier가 제대로 적용되지 않고 있던 것을 이제야 알아서 포매터 설정을 한참 수정했어요..

2021-08-19 15:52 UTC, yourankim commented on src/pages/sample.tsx
> +    async function getList() {
제안해주신대로 수정해보았어요! `useEffect 안에 함수를 정의하면 이펙트 실행될 때마다 함수가 새로 만들어지고, useCallback을 쓰면 의존값이 바뀌기 전까지는 계속 동일한 함수를 사용할 수 있다` - > 이렇게 이해하면 맞는 걸까요? 
에러 처리도 고민해보겠습니닷.. 괜찮으시다면 요 부분 다음에 따로 질문을 드려도 될까요? @rostradamus

2021-08-19 15:54 UTC, yourankim commented on src/pages/sample.tsx
> +      {list.map((item: Data) => <li>{item.message}</li>)}
수정했습니다 감사합니다!

2021-08-19 15:56 UTC, yourankim commented
> 👍


제가 너무 늦게 확인했어요ㅠㅠ꼼꼼히 리뷰해주셔서 감사해요 정말 많은 도움이 되었습니다!!

2021-08-19 16:00 UTC, rostradamus commented on src/pages/sample.tsx
> +    async function getList() {
> useEffect 안에 함수를 정의하면 이펙트 실행될 때마다 함수가 새로 만들어지고, useCallback을 쓰면 의존값이 바뀌기 전까지는 계속 동일한 함수를 사용할 수 있다
넵 맞습니다 :) 제가 설명 드릴 수 있는 부분이라면 얼마든지 답변드리겠습니다! 언제든지 질문주세요~

2021-08-19 16:40 UTC, merged